### ISSUE TITLE
Issue getting sidebery.json to apply

### ISSUE THREAD

**Issue by paulr24** [TheAnimatrix/AnimatrixZen#1]
Love the theme! I am experiencing a problem though. After I import sidebery.json I can briefly see my tabs change to the proper theme, but only for a fraction of a second and then it reverts back to my previous (stock?) theme and looks like this:

![image](https://github.com/user-attachments/assets/a58411b2-d68a-49a0-b1b3-4e14c54f6971)

Any idea how I can fix this?

**Comment by TheAnimatrix** [comment]
Interesting, Have you fixed it ? Did you use the custom built extension ?
